### ISSUE TITLE
Add the concept of an object-store UUID to identify it

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/disk-objectstore#11]
E.g. to associate it with an existing DB, or to uniquely refer to it.

This could be generated during the `init_container` call and then stored in the repository config json

**Comment by giovannipizzi** [comment]
Also:
- add a version of the repository (or of the library that wrote it)
- during `init`, make sure the configuration makes sense and there are no unexpected values

**Comment by giovannipizzi** [comment]
@sphuber do we want this in AiiDA, so we know we are pointing to the right container? A bit like the UUID for RabbitMQ, or the same for the DB (I don't know if we have one implemented yet).

Also, should it be generated when creating the container, or should it be settable?

**Comment by sphuber** [comment]
I don't think it is necessary. We don't have it now, after all, currently we also just have an absolute filepath in the profile pointing to the database. However, it might actually be a useful feature, and will allow us to perform some sanity checks. If we implement this, I would definitely lean to *not* allowing a user to determine the UUID, we just generate one. For the interface in the `disk-objectstore` you may want to allow passing in the filepath and the UUID of a container when initializing it and `disk-objectstore` will then perform the consistency check. I guess the construction of a container would return a UUID then, which we can store in AiiDA's database settings to make the connection when we create a container for a profile the first time
