### ISSUE TITLE
Release 1.0 after testing

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/disk-objectstore#155]
* [x] remove deprecated stuff
* [ ] stress test on a big DB (e.g. the new auto packing) from @zhubonan 
* [x] test with `aiida-core`
* [x] add changelog
* [x] release

Then, adapt in to AiiDA the use of this library (both the dependency, but also check its use and possibly adapt backward-incompatible things such as Path instead of str for paths, or data classes instead of dicts

**Comment by sphuber** [comment]
Test against `aiida-core` is successful, see: https://github.com/sphuber/aiida-core/actions/runs/6265535462/job/17014586105

**Comment by sphuber** [comment]
Prepared changelog in https://github.com/aiidateam/disk-objectstore/tree/release/1.0
