### ISSUE TITLE
Test performance on remotely-mounted filesystem

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/disk-objectstore#17]
Test performance also on remotely-mounted object-store filesystem (in particular, efficiency in random-access to a given position of a file, in moving objects from the sandbox, and in repacking/appending).

Test both a OpenStack Swift implementation, and an S3 implementation.

Assess if this is the correct approach, or maybe this does not work, but reading is still efficient from packs, and then it might make sense to pack locally, push the packs to the object store folder, and then use it in read-only.

**Comment by giovannipizzi** [comment]
Here are the current results, tested with an OpenStack Swift object store implementation, providing also a S3 interface, made available at the Swiss Supercomputing Centre CSCS.

I tested two options:

## Mounting using [svfs](https://github.com/ovh/svfs)
This is a FUSE library that uses the native Swift interface. 
Important note: this is probably deprecated now! There have been no releases in the past 3-4 years, and the repository is archived.

For reference, this was installed using:
```bash
sudo apt install ruby
wget https://github.com/ovh/svfs/releases/download/v0.9.1/svfs_0.9.1_amd64.deb
sudo dpkg -i svfs_0.9.1_amd64.deb
```
Then I logged it and created a token, and set up the env vars with:
```bash
export OS_STORAGE_URL=https://object.cscs.ch/v1/AUTH_$OS_PROJECT_ID
export OS_AUTH_TOKEN=$OS_TOKEN
```
and finally mounted with
```bash
mount.svfs random_device_name PATH_TO_MOUNT_DESTINATION -o allow_other=0,container=CONTAINER NAME
```

### Results
This is not a viable solution, beside the deprecation problem of the library.

In fact, it is not possible to append to a file, nor seek into a file, and [there not seem to be flags to do this](https://github.com/ovh/svfs#prefetch-options)

For instance, in python, I get:
```
In [1]: f = open('a.txt', 'a')                                                  
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-1-d632866af84d> in <module>
----> 1 f = open('a.txt', 'a')

OSError: [Errno 95] Operation not supported: 'a.txt'
```

```
In [2]: f = open('a.txt', 'w')                                                  

In [3]: f.seek(3)                                                               
---------------------------------------------------------------------------
UnsupportedOperation                      Traceback (most recent call last)
<ipython-input-3-d40022ec6b0a> in <module>
----> 1 f.seek(3)

UnsupportedOperation: underlying stream is not seekable
```

## Mounting using [s3fs](https://github.com/s3fs-fuse/s3fs-fuse)
This is a much more mature FUSE library, using the S3 protocol. It also says in the README that it supports appending, some levels of caching, and more.
**IMPORTANT**: *Note that the concepts of appending or moving do not exist! They are emulated by the library by creating new objects*.

After setting the env vars with the token, the AUTH_URL etc, I run
```
openstack ec2 credentials create
```
that prints the token.
Then I put them in a file as follows:
```
echo ACCESS_KEY_ID:SECRET_ACCESS_KEY > ${HOME}/.passwd-s3fs
chmod 600 ${HOME}/.passwd-s3fs
```

To use the other S3 libraries as `boto`, instead, add a `~/.aws/credentials` file with the following three lines:
```
[default]
aws_access_key_id = your_access_key_id
aws_secret_access_key = your_secret_access_key
```

### Results
Creating a new object (even just touching a new file) is *very* slow. Appending to an existing file is actually faster (note that I was running from a powerful VM inside the same CSCS network).

Some results:
```
$ echo "a" > d.txt

$ time echo "a" >> d.txt

real	0m0.653s
user	0m0.000s
sys	0m0.000s

$ time echo "a" > e.txt

real	0m1.807s
user	0m0.000s
sys	0m0.000s

$ time echo "a" > e.txt

real	0m0.650s
user	0m0.000s
sys	0m0.000s

$ time echo "a" > f.txt

real	0m1.777s
user	0m0.000s
sys	0m0.000s
```

So it's about ~1.8s for new objects, ~0.7s when appending.

This already clearly gives limits to the performance (that will be very poor) of this or any other implementation where each file is an object in the object store.

Anyway, the library works as expected on top of it, with these timings:
```
Clearing the container...
Currently known objects: 0 packed, 0 loose
Pack objects on disk: 0
Generating 100 files in memory...
Done. Total size: 50805 bytes (~0.048 MB).
Time to store 100 loose objects: 612.0 s
Time to retrieve 100 loose objects: 49.61 s
Object store size info:
- total_size_loose              : 50805
- total_size_packed             : 0
- total_size_packed_on_disk     : 0
- total_size_packfiles_on_disk  : 0
- total_size_packindexes_on_disk: 12288
Time to pack all loose objects: 1.159e+03 s
Object store size info:
- total_size_loose              : 0
- total_size_packed             : 50805
- total_size_packed_on_disk     : 50805
- total_size_packfiles_on_disk  : 50805
- total_size_packindexes_on_disk: 20480
Time to retrieve 100 packed objects in random order WITH ONE BULK CALL: 28.964391708374023 s
Time to retrieve 100 packed objects in random order WITH 10 BULK CALLS: 34.27432322502136 s
Time to retrieve 100 packed objects in random order: 34.960145473480225 s
All tests passed
```
The performance is clearly bad, also when retrieving objects from packs.

### Notes
This might be anyway due to the fact that there are many pack files.

What remains to be tested is the time to random access a big file, in particular how seeking into a big file works, if it can just retrieve a chunk or all of it, and how big are the chunks that are cached, and how large the chunks can be.

Anyway, even a request for a chunk will have a big latency, so the question remains if there is a way to get better performance if we really want to use an object store.

My current idea would be to use the object store only to keep files in read-only mode, pack locally and then push to the OS, and either check if the mounting library can be tuned to use large caches (maybe mounting in read-only mode can help?), or just fetch a local copy and work on it.

One parallel question is if the performance hit is in the Sqlite DB read, on in reading the objects (to be checked). If the issue is with the DB, one might think to mount the pack and symlink them, and keep the SQLite DB in a local FS.

**Comment by giovannipizzi** [comment]
Here are some additional study and results on performance for reads:

## Creating a big 2GB file
```
./create-big-file.py
File opened in 1.8334405422210693 s
2048 MB written in 85.3022198677063 seconds
(24MB/s)
```

## Reading the same big file
```
time cat s3fs-mount/bigfile.dat > /dev/null
real	0m33.349s
```

```
./umount.sh
./mount.sh
time cat s3fs-mount/bigfile.dat > /dev/null
real	0m32.572s
```

```
time cat s3fs-mount/bigfile.dat > /dev/null
real	0m31.413s
```
The speed is roughly 63MB/s and it does not matter if I unmount it (I wanted to check if there is some long-lived cache, it seems there isn't).

## Reading data at a given offset 
```
$ ./fetch-big-file.py
File opened in 0.22202777862548828 s
100 bytes read in 0.6143879890441895 seconds
100 bytes with an additional offset of 500 read in 0.00011682510375976562 seconds
File closed in 0.0016109943389892578 seconds
```

```
$ ./fetch-big-file.py
File opened in 0.2569596767425537 s
Went to offset 1073741824 in 2.3365020751953125e-05 seconds
100 bytes read in 0.6589374542236328 seconds
100 bytes with an additional offset of 500 read in 0.0002560615539550781 seconds
File closed in 0.0019474029541015625 seconds
```

```
$ ./fetch-big-file.py
File opened in 0.2780942916870117 s
Went to offset 1073741824 in 2.9802322387695312e-05 seconds
100 bytes read in 0.6467843055725098 seconds
100 bytes with an additional offset of 5000 read in 0.0002307891845703125 seconds
File closed in 0.003162860870361328 seconds
```

```
$ ./fetch-big-file.py
File opened in 0.24104881286621094 s
Went to offset 1073741824 in 5.269050598144531e-05 seconds
100 bytes read in 0.6265418529510498 seconds
100 bytes with an additional offset of 50000 read in 0.00031495094299316406 seconds
File closed in 0.002343416213989258 seconds
```

```
$ ./fetch-big-file.py
File opened in 0.2407548427581787 s
Went to offset 1073741824 in 3.933906555175781e-05 seconds
100 bytes read in 0.6929028034210205 seconds
100 bytes with an additional offset of 500000 read in 0.0002410411834716797 seconds
File closed in 0.0025687217712402344 seconds
```

```
$ ./fetch-big-file.py
File opened in 0.265308141708374 s
Went to offset 1073741824 in 2.3365020751953125e-05 seconds
100 bytes read in 0.6436514854431152 seconds
100 bytes with an additional offset of 5000000 read in 0.00031256675720214844 seconds
File closed in 0.0033168792724609375 seconds
```

```
$ ./fetch-big-file.py
File opened in 0.2847025394439697 s
Went to offset 1073741824 in 2.6226043701171875e-05 seconds
100 bytes read in 0.6557683944702148 seconds
100 bytes with an additional offset of 50000000 read in 0.00027871131896972656 seconds
File closed in 0.0028493404388427734 seconds
```

```
$ ./fetch-big-file.py
File opened in 0.23730134963989258 s
Went to offset 1073741824 in 3.6716461181640625e-05 seconds
100 bytes read in 0.6238281726837158 seconds
100 bytes with an additional offset of 52000000 read in 0.00031757354736328125 seconds
File closed in 0.0026552677154541016 seconds
```

```
$ ./fetch-big-file.py
File opened in 0.16971468925476074 s
Went to offset 1073741824 in 3.337860107421875e-05 seconds
100 bytes read in 0.6933572292327881 seconds
100 bytes with an additional offset of 53000000 read in 0.6725606918334961 seconds
File closed in 0.0026552677154541016 seconds
```

Discussion: this might be compatible with the fact that when opening, the filesystem fetches a preliminary buffer, justifying the initial 0.6s.  Then it seems to read a block of about 52MB, and caches it, so reads from the same block are then quite fast (it's possible that the block size is larger, as this number is a bit weird, and it has a "page size", so it fetches also a bit before the offset I asked for).

Also: Apparently the buffer is 'destroyed' upon closing the file, as a sizeable time is needed again when reopening the same file. So it might be beneficial to keep the pack files open.

### Reading in random order
Here I try to prove the same result by opening a file and then having random reads from it.
As it is visible the time oscillates between ~0.6s (probably when it fetches a "page") to 0.1ms (when it's already cached):
```
$ ./fetch-big-file-random.py
File opened in 0.23392057418823242 s
100 bytes read at offset 1947559672 in 0.711890697479248 seconds
100 bytes read at offset 357643288 in 0.6958115100860596 seconds
100 bytes read at offset 609278303 in 1.9357304573059082 seconds
100 bytes read at offset 2134884445 in 0.7221231460571289 seconds
100 bytes read at offset 1483228949 in 0.7791919708251953 seconds
100 bytes read at offset 923871474 in 0.7089576721191406 seconds
100 bytes read at offset 83043142 in 0.7348387241363525 seconds
100 bytes read at offset 1345247205 in 0.7119061946868896 seconds
100 bytes read at offset 634318594 in 0.00015807151794433594 seconds
100 bytes read at offset 341348923 in 0.38927388191223145 seconds
100 bytes read at offset 865498106 in 0.7049028873443604 seconds
100 bytes read at offset 1030190293 in 0.700446367263794 seconds
100 bytes read at offset 2145000644 in 0.00016880035400390625 seconds
100 bytes read at offset 609386350 in 9.822845458984375e-05 seconds
100 bytes read at offset 816420131 in 0.6015491485595703 seconds
100 bytes read at offset 195964990 in 0.7852489948272705 seconds
100 bytes read at offset 1892531319 in 0.7511641979217529 seconds
100 bytes read at offset 1129389259 in 0.8137998580932617 seconds
100 bytes read at offset 955553178 in 0.00014829635620117188 seconds
100 bytes read at offset 306928252 in 0.46568965911865234 seconds
100 bytes read at offset 596857966 in 0.5029318332672119 seconds
100 bytes read at offset 963015210 in 0.0001163482666015625 seconds
100 bytes read at offset 1870939438 in 0.3600447177886963 seconds
100 bytes read at offset 1150054116 in 0.00012612342834472656 seconds
100 bytes read at offset 1289809152 in 0.737135648727417 seconds
100 bytes read at offset 1853631197 in 0.35086631774902344 seconds
100 bytes read at offset 136223790 in 0.6831955909729004 seconds
100 bytes read at offset 1014018624 in 0.30544209480285645 seconds
100 bytes read at offset 1098655385 in 0.440779447555542 seconds
100 bytes read at offset 1981898844 in 0.00024366378784179688 seconds
100 bytes read at offset 2043583507 in 0.6902182102203369 seconds
100 bytes read at offset 1350005704 in 0.00026702880859375 seconds
100 bytes read at offset 1397328774 in 0.00018906593322753906 seconds
100 bytes read at offset 1875349871 in 0.0003948211669921875 seconds
100 bytes read at offset 89545177 in 0.00021028518676757812 seconds
100 bytes read at offset 1525409154 in 0.0001628398895263672 seconds
100 bytes read at offset 1731939510 in 0.7802331447601318 seconds
100 bytes read at offset 1060330002 in 0.0001862049102783203 seconds
100 bytes read at offset 1732016594 in 0.00012874603271484375 seconds
100 bytes read at offset 2068213757 in 0.00012159347534179688 seconds
100 bytes read at offset 533694428 in 0.605139970779419 seconds
100 bytes read at offset 4779996 in 0.8351280689239502 seconds
100 bytes read at offset 1664135591 in 0.6079790592193604 seconds
100 bytes read at offset 1852641490 in 0.1851189136505127 seconds
100 bytes read at offset 2128710469 in 0.28339457511901855 seconds
100 bytes read at offset 1935539239 in 0.00010752677917480469 seconds
100 bytes read at offset 179396091 in 6.914138793945312e-05 seconds
100 bytes read at offset 1083090784 in 0.39987778663635254 seconds
100 bytes read at offset 1931045452 in 0.00015306472778320312 seconds
100 bytes read at offset 2084466102 in 0.00018739700317382812 seconds
100 bytes read at offset 849454905 in 0.00021195411682128906 seconds
100 bytes read at offset 36419555 in 8.225440979003906e-05 seconds
100 bytes read at offset 228447964 in 0.00011324882507324219 seconds
100 bytes read at offset 1731357656 in 0.17884516716003418 seconds
100 bytes read at offset 1298673997 in 0.00014495849609375 seconds
100 bytes read at offset 761629475 in 0.7618091106414795 seconds
100 bytes read at offset 1581874150 in 0.6880624294281006 seconds
100 bytes read at offset 282332297 in 0.4579482078552246 seconds
100 bytes read at offset 726813952 in 0.47531938552856445 seconds
100 bytes read at offset 1830748507 in 0.4228994846343994 seconds
100 bytes read at offset 2124504193 in 0.30403804779052734 seconds
100 bytes read at offset 52357624 in 0.00023794174194335938 seconds
100 bytes read at offset 1278841082 in 1.0706157684326172 seconds
100 bytes read at offset 1051019528 in 0.0002491474151611328 seconds
100 bytes read at offset 1233701760 in 0.9539909362792969 seconds
100 bytes read at offset 218462289 in 0.0002789497375488281 seconds
100 bytes read at offset 573808795 in 0.00010657310485839844 seconds
100 bytes read at offset 847717905 in 0.00011157989501953125 seconds
100 bytes read at offset 1023178081 in 5.936622619628906e-05 seconds
100 bytes read at offset 353693169 in 7.462501525878906e-05 seconds
100 bytes read at offset 745830537 in 0.0001518726348876953 seconds
100 bytes read at offset 1412439339 in 1.0327136516571045 seconds
100 bytes read at offset 1635466695 in 0.7401645183563232 seconds
100 bytes read at offset 1693335361 in 0.00014352798461914062 seconds
100 bytes read at offset 235581343 in 0.00012803077697753906 seconds
100 bytes read at offset 401116483 in 7.176399230957031e-05 seconds
100 bytes read at offset 63343945 in 0.42454028129577637 seconds
100 bytes read at offset 185460953 in 0.00015854835510253906 seconds
100 bytes read at offset 401036035 in 0.00010085105895996094 seconds
100 bytes read at offset 47008185 in 8.845329284667969e-05 seconds
100 bytes read at offset 551472608 in 7.2479248046875e-05 seconds
100 bytes read at offset 895126128 in 9.107589721679688e-05 seconds
100 bytes read at offset 1775207698 in 0.00010585784912109375 seconds
100 bytes read at offset 1319603798 in 8.416175842285156e-05 seconds
100 bytes read at offset 1055898303 in 6.723403930664062e-05 seconds
100 bytes read at offset 433503593 in 0.8430712223052979 seconds
100 bytes read at offset 858467657 in 0.0001595020294189453 seconds
100 bytes read at offset 1839621917 in 0.00013899803161621094 seconds
100 bytes read at offset 1477980 in 0.29141712188720703 seconds
100 bytes read at offset 1468361691 in 0.3742237091064453 seconds
100 bytes read at offset 362155856 in 0.0001201629638671875 seconds
100 bytes read at offset 403435752 in 7.772445678710938e-05 seconds
100 bytes read at offset 915478901 in 6.461143493652344e-05 seconds
100 bytes read at offset 383002533 in 6.437301635742188e-05 seconds
100 bytes read at offset 1710326279 in 9.584426879882812e-05 seconds
100 bytes read at offset 328832982 in 8.130073547363281e-05 seconds
100 bytes read at offset 201441928 in 7.367134094238281e-05 seconds
100 bytes read at offset 722447387 in 0.28914761543273926 seconds
100 bytes read at offset 305685421 in 0.0001418590545654297 seconds
100 bytes read at offset 1282476314 in 8.416175842285156e-05 seconds
```

## Opening many files
It might be worth investigating having the disk-objectstore in read-only mode, with packing done on a real disk (otherwise it would be impossibly slow), but then allowing to read from the pack files.
Here I want to check if I can open many files at the same time.

I tested and I can open 300 files at the same time (on linux), without problems. It takes about ~0.6s to open them. Closing is faster. This is consistent with what is written above.
Therefore, a possible strategy would be to have a flag to keep all files open (possibly False by default to avoid problems on Mac). If we implement this then we can do some benchmarks.

Open questions:
- how big is the cache? How long it persists? (I could open a very large file, read from top to bottom, and then start over from offset zero, and check if the time to read the first bytes is big or small)
- Can we tune the size of the blocks that are retrieved? (This is possibly less relevant if we use in read-only mode, but could be relevant when writing).
- Check which errors you (should) get from the disk-objectstore if the folder unmounts due to a network problem.

**Comment by giovannipizzi** [comment]
A few additional comments:
- there is [goofys](https://github.com/kahing/goofys), designed exactly to increase performance over s3fs. However, it gives less guarantees (we should check if it's ok) and anyway the performance is better but still way slower than a real disk (which to me seems obvious, anyway).
- mounting read-only does not seem to affect performance from some preliminary tests
- one important option to consider, if there is enough space on the disk of the computer and it's ok to keep data locally instead of fetching in real time from the remote object store, is to use the [`use_cache` option](https://github.com/s3fs-fuse/s3fs-fuse/blob/005a684600f83a784c526ada078ac807e5e19633/doc/man/s3fs.1#L73) of s3fs, [that says](https://github.com/s3fs-fuse/s3fs-fuse/blob/005a684600f83a784c526ada078ac807e5e19633/doc/man/s3fs.1#L361):
> If enabled via the "use_cache" option, s3fs automatically maintains a local cache of files in the folder specified by use_cache. Whenever s3fs needs to read or write a file on S3, it first downloads the entire file locally to the folder specified by use_cache and operates on it. When fuse_release() is called, s3fs will re-upload the file to S3 if it has been changed. s3fs uses MD5 checksums to minimize downloads from S3.

**Comment by giovannipizzi** [comment]
I tried `./fetch-big-file-random.py` with the `use_cache` option. Indeed, it immediately creates a big file in the cache directory, but if fetches only a few tens MB at a time. So, the first time you run, you get essentially the same performance as above. However, running it multiple times, will eventually fetch all blocks, and then any random read is extremely fast (~0.1ms). 
The default behaviour is not to delete the cache (there is a flag for that).
To be checked what happens if the disk space ends (maybe good to put the cache on a different partition?).
If space permits, probably this is the best option for distributed web servers? Maybe is also a bit more robust w.r.t. network temporary issues, if the file is already cached.

**Comment by espenfl** [comment]
Great work Giovanni. Have you tried to setup Swift on your local computer and run the benchmarks there? I think it is important to also get benchmarks when you sit on the storage network. For many implementations of production AiiDA, this would indeed be the case. E.g. AiiDA would sit as an instance in a OpenStack system which runs on Infiniband. This houses both the object store and provisioned HPC resources.

Also, we should consider to get some feedback from e.g. SwiftStack regarding what can be done and what to expect for performance.

**Comment by giovannipizzi** [comment]
I run all tests from a powerful VM (at CSCS, 64GB RAM, 16 VCPUs, with Ubuntu) in the same OpenStack cluster as the Swift Object Store. So there shouldn't be bottlenecks on the network side.

**Comment by espenfl** [comment]
Thanks for the details. Hard to know how their system really works so running these tests on a local computer gives you the object store overhead without the network as well.

Also, note that mounting object store as a file system is not really the way to go and does not really represent how it should operate in production. It should be used as an API. But then the performance tests will be more involved as we would have to write an interface. Maybe we should do this? I might have time to contribute at some time as I have other interests in this as well.

If we really need to mount it, notice comments about s3fs having a lot of overhead (that it needs to be tuned and the alternative riofs):
https://serverfault.com/questions/396100/s3fs-performance-improvements-or-alternative
https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-s3fs
https://github.com/skoobe/riofs

**Comment by giovannipizzi** [comment]
Closing this issue - I think it is a great resource for testing and future reference, but at the moment the goal is not to use it over a mounted S3 and there is now in AiiDA an implementation replacing this library with calls to S3.
