### ISSUE TITLE
Describe correct procedure for backups and test it

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/disk-objectstore#20]
In particular, if rsync is used during packing, check if there is the risk of having corrupted data (e.g. if the pack files are transferred before the index and this then refers to missing data, if the loose files are not transferred but the packs have been already transferred, etc.)

**Comment by giovannipizzi** [comment]
This is very important - note that there is an official procedure also to backup SQLite files, probably one cannot just run rsync on them

**Comment by giovannipizzi** [comment]
@eimrek is working on the docs for AiiDA backups. Good to back port something in this repo, or at least refer to those (AiiDA) docs from the disk-objectstore docs.

**Comment by eimrek** [comment]
Thanks. Possibly makes sense to move the dos backup function to this repo https://github.com/aiidateam/aiida-core/blob/backup-script/aiida/storage/psql_dos/backend.py#L429

**Comment by eimrek** [comment]
done in #161
